
version: "3.9"

services:

  elt:
    build: database
    # by default, don't do anything
    command: "noop"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_HOSTNAME: ${POSTGRES_DB}
      PYSPARK_SUBMIT_ARGS: '--packages org.postgresql:postgresql:42.5.0 pyspark-shell'
      PROJECT_PATH: /opt/kclp
    networks:
      - all
    volumes:
      - ./database:/opt/kclp

  docs:
    build:
      context: .
    command: "serve-docs"
    ports:
      - "8000:8000"
    volumes:
      - ./database:/opt/kclp

  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 2s
      retries: 3
    image: postgres:13.10
    networks:
      - all
    ports:
      - "5433:5432"
    restart: always
    #user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/data:/data

  frontend:
    build: frontend
    depends_on:
      - db
    environment:
      FLASK_DEBUG: 1
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: >-
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}/postgres

    networks:
      - all
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./frontend:/usr/src/app/frontend

networks:
  all:

volumes:
  db-data: {}
